# Estágio 1: Build da aplicação
FROM node:14-alpine AS build
WORKDIR /app

# Copia os arquivos de dependências
COPY package.json package-lock.json ./
RUN npm install

# Copia o restante dos arquivos e gera o build de produção
COPY . .
RUN npm run build -- --prod

# Estágio 2: Servindo a aplicação com Nginx
FROM nginx:stable-alpine

# Copia o build do estágio anterior para a pasta do Nginx
# Substitua 'nome-do-seu-projeto' pelo nome definido no angular.json
COPY --from=build /app/dist/appGestaoFinanceira /usr/share/nginx/html

# Copia sua configuração personalizada para o Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf 

# Exposição da porta padrão
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]